# Generated by Django 5.2.5 on 2025-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=24)),
                ('Email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
                ('Company_name', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField(max_length=10)),
                ('district_name', models.CharField(max_length=30)),
                ('State', models.TextField(max_length=24)),
            ],
        ),
    ]
