# Generated by Django 5.2.5 on 2025-08-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='State',
            field=models.CharField(max_length=24),
        ),
    ]
