# Generated by Django 5.2.5 on 2025-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0002_alter_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='agreeToTerms',
            field=models.BooleanField(default=False),
        ),
    ]
