# Generated by Django 5.2.5 on 2025-08-26 04:58

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0003_buyer_agreetoterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=builtins.id, related_name='items', serialize=False, to='Apibuyer.buyer')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('item_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('model_number', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=50, verbose_name='')),
                ('description', models.TextField(max_length=400)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
