# Generated by Django 5.2.5 on 2025-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
