# Generated by Django 5.2.5 on 2025-08-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0006_products_id_alter_products_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='Products/', verbose_name=''),
        ),
    ]
