# Generated by Django 5.2.5 on 2025-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='container',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='fssai',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='maxmium_life',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='object_form',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pack_of',
            field=models.IntegerField(blank=True, max_length=10.0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
