# Generated by Django 5.2.5 on 2025-09-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0008_products_container_products_fssai_products_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='fssai',
            new_name='fssai_number',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='maxmium_life',
            new_name='maxmium_shelf_life',
        ),
    ]
