# Generated by Django 5.2.5 on 2025-09-08 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apibuyer', '0009_rename_fssai_products_fssai_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pack_of',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
